# Generated by Django 6.1.1 on 2026-09-29 05:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last Name', max_length=50)),
                ('profile', models.CharField(blank=True, db_column='Profile', max_length=255, null=True)),
                ('bio', models.CharField(blank=True, db_column='Bio', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(db_column='RouteID', primary_key=True, serialize=False)),
                ('route_name', models.CharField(db_column='RouteName', max_length=50)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('total_distance', models.DecimalField(db_column='TotalDistance', decimal_places=2, max_digits=5)),
                ('elevation', models.DecimalField(db_column='Elevation', decimal_places=2, max_digits=6)),
                ('estimated_time', models.IntegerField(db_column='Estimated Time:')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('account', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Route',
            },
        ),
        migrations.CreateModel(
            name='RouteCoordinates',
            fields=[
                ('route_cd_id', models.AutoField(db_column='RouteCD ID', primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(db_column='Latitude', decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(db_column='Longtitude', decimal_places=8, max_digits=11)),
                ('elevation', models.IntegerField(db_column='Elevation')),
                ('point_order', models.IntegerField(db_column='PointOrder')),
                ('route', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='accounts.route')),
            ],
            options={
                'db_table': 'RouteCoordinates',
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('route_wp_id', models.AutoField(db_column='RouteWP ID', primary_key=True, serialize=False)),
                ('location_spot_name', models.CharField(db_column='Location SpotName', max_length=50)),
                ('spot_description', models.TextField(blank=True, db_column='SpotDescription', null=True)),
                ('spot_image', models.CharField(blank=True, db_column='SpotImage', max_length=255, null=True)),
                ('latitude', models.DecimalField(db_column='Latitude', decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(db_column='Longtitude', decimal_places=8, max_digits=11)),
                ('route', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='accounts.route')),
            ],
            options={
                'db_table': 'RouteWaypoints',
            },
        ),
        migrations.CreateModel(
            name='UserCompletedRoute',
            fields=[
                ('user_cr_id', models.AutoField(db_column='UserCR ID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_column='CompletedAt')),
                ('account', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='completed_routes', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(db_column='RouteID', on_delete=django.db.models.deletion.CASCADE, related_name='user_completions', to='accounts.route')),
            ],
            options={
                'db_table': 'UserCompleted Routes',
            },
        ),
    ]
